### ISSUE TITLE
Watching replays

### ISSUE THREAD

**Issue by morghan** [Rosalila/FlatshotAssets#2]
It stores scores and I was able to watch replays, but then I hit a new high score, stored it but _crashed everytime I tried to watch my replay._ I was able to watch everybody else's replays though. This was the first stage of theTutorial

**Comment by Turupawn** [comment]
I also tried to watch the replay and the game crashed. Thanks for leaving the replay and please do not upload a new one so I can see what's happening.

**Comment by Turupawn** [comment]
I don't know why the replay was not uploaded to steam but at least right now the game won't crash when trying to view a non existent replay:
https://github.com/Rosalila/STG/commit/857d89c10182941b89217abb22d057474df11450

I guess that a "Replay could not be saved. Try again?" and a "The replay was not found" messages would be enough.

**Comment by Turupawn** [comment]
The "Replay was not found notification" was added here:
https://github.com/Rosalila/STG/commit/1dcef3dbfa1855450583f10de86f685303e187a0

And the "Try again?" message on a failed upload score and replay was added here:
https://github.com/Rosalila/STG/commit/3d9ce41a188cecafc6c7166255d02e43e1e01e83
